package gui;

import controller.AdministratorController;
import controller.CommonController;
import controller.LoginController;
import gui.utils.RandomPass;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.*;


/**
 *
 * @author Alexandru
 */
public class AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel(LoginController lcontroller,AdministratorController controller,String loggedUser,AdminMainFrame amf) {
        
        t = new Timer(2000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jLabelDoneIconRU.setVisible(false);
                jLabelDoneIconRL.setVisible(false);
            }
        });
        t.setRepeats(false);
        
        generator = new RandomPass(6);
        this.controller = controller;
        this.commonController = new CommonController();
        this.loginController = lcontroller;
        this.loggedUser = loggedUser;
        this.amf = amf;
        initComponents();
        jLabelGreeting.setText("Buna "+loggedUser);
        //pentru RU:
        jLabelDoneIconRU.setVisible(false);
        jLabelPostOcupat.setVisible(false);
        jTextFieldPostOcupat.setVisible(false);
        jCheckBoxDirectorDepartament.setVisible(false);
        jLabelSpecializareDoctorand.setVisible(false);
        jTextFieldSpecializareDoctorand.setVisible(false);
        jTableRU.setModel(commonController.getResursaUmanaTableModel());
        
        
        
        //pentru RL
        jLabelDoneIconRL.setVisible(false);
        jTextFieldCodSalaRL.setEditable(false);
        jTextFieldNrLocuriRL.setEditable(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRL = new javax.swing.ButtonGroup();
        buttonGroupRU = new javax.swing.ButtonGroup();
        jPanelTopPanel = new javax.swing.JPanel();
        jLabelGreeting = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelRU = new javax.swing.JPanel();
        jScrollPaneRU = new javax.swing.JScrollPane();
        jTableRU = new javax.swing.JTable();
        jLabelNume = new javax.swing.JLabel();
        jLabelPrenume = new javax.swing.JLabel();
        jLabelTelefon = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelInterese = new javax.swing.JLabel();
        jTextFieldNume = new javax.swing.JTextField();
        jTextFieldPrenume = new javax.swing.JTextField();
        jTextFieldTelefon = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldInterese = new javax.swing.JTextField();
        jButtonAdaugaRU = new javax.swing.JButton();
        jButtonGolesteCampuriRU = new javax.swing.JButton();
        jLabelSeAdaugaUn = new javax.swing.JLabel();
        jRadioButtonCadruDidactic = new javax.swing.JRadioButton();
        jRadioButtonDoctorand = new javax.swing.JRadioButton();
        jRadioButtonCercetator = new javax.swing.JRadioButton();
        jRadioButtonPersonalAdministrativ = new javax.swing.JRadioButton();
        jLabelPostOcupat = new javax.swing.JLabel();
        jTextFieldPostOcupat = new javax.swing.JTextField();
        jCheckBoxDirectorDepartament = new javax.swing.JCheckBox();
        jLabelSpecializareDoctorand = new javax.swing.JLabel();
        jTextFieldSpecializareDoctorand = new javax.swing.JTextField();
        jLabelDoneIconRU = new javax.swing.JLabel();
        jPanelRF = new javax.swing.JPanel();
        jLabelResurseDisponibile = new javax.swing.JLabel();
        jScrollPaneRF = new javax.swing.JScrollPane();
        jTableResurseFinanciare = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSursaFonduri = new javax.swing.JTextField();
        jTextFieldCuantum = new javax.swing.JTextField();
        jTextFieldMoneda = new javax.swing.JTextField();
        jButtonAdaugaRF = new javax.swing.JButton();
        jButtonRenuntaRF = new javax.swing.JButton();
        jPanelRL = new javax.swing.JPanel();
        jRadioButtonAdaugaEchipament = new javax.swing.JRadioButton();
        jRadioButtonAdaugaSala = new javax.swing.JRadioButton();
        jLabelTipEchipament = new javax.swing.JLabel();
        jLabelModelEchipament = new javax.swing.JLabel();
        jLabelCodSala = new javax.swing.JLabel();
        jLabelNumarLocuri = new javax.swing.JLabel();
        jTextFieldTipEchipamentRL = new javax.swing.JTextField();
        jTextFieldModelEchipamentRL = new javax.swing.JTextField();
        jTextFieldCodSalaRL = new javax.swing.JTextField();
        jTextFieldNrLocuriRL = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableEchipamente = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableSali = new javax.swing.JTable();
        jButtonAdaugaRL = new javax.swing.JButton();
        jButtonGolesteCampuriRL = new javax.swing.JButton();
        jLabelDoneIconRL = new javax.swing.JLabel();
        jPanelSF = new javax.swing.JPanel();
        jPanelOR = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelGreeting.setText("Buna ");

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopPanelLayout = new javax.swing.GroupLayout(jPanelTopPanel);
        jPanelTopPanel.setLayout(jPanelTopPanelLayout);
        jPanelTopPanelLayout.setHorizontalGroup(
            jPanelTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTopPanelLayout.setVerticalGroup(
            jPanelTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelGreeting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout))
        );

        jTableRU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nume", "Prenume", "Telefon", "eMail", "Interese"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneRU.setViewportView(jTableRU);

        jLabelNume.setText("Nume:");

        jLabelPrenume.setText("Prenume:");

        jLabelTelefon.setText("Telefon:");

        jLabelEmail.setText("eMail:");

        jLabelInterese.setText("Interese:");

        jTextFieldNume.setNextFocusableComponent(jTextFieldPrenume);

        jTextFieldPrenume.setNextFocusableComponent(jTextFieldTelefon);

        jTextFieldTelefon.setNextFocusableComponent(jTextFieldEmail);

        jTextFieldEmail.setNextFocusableComponent(jTextFieldInterese);

        jTextFieldInterese.setToolTipText("Domeniile de interes se vor adauga cu \" ; \" intre ele.");
        jTextFieldInterese.setNextFocusableComponent(jTextFieldPostOcupat);

        jButtonAdaugaRU.setText("Adauga");
        jButtonAdaugaRU.setToolTipText("Adauda datele introduse in baza de date");
        jButtonAdaugaRU.setNextFocusableComponent(jButtonGolesteCampuriRU);
        jButtonAdaugaRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdaugaRUActionPerformed(evt);
            }
        });

        jButtonGolesteCampuriRU.setText("Golire campuri");
        jButtonGolesteCampuriRU.setToolTipText("Goleste toate campurile completate");
        jButtonGolesteCampuriRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGolesteCampuriRUActionPerformed(evt);
            }
        });

        jLabelSeAdaugaUn.setText("Se adauga un:");

        buttonGroupRU.add(jRadioButtonCadruDidactic);
        jRadioButtonCadruDidactic.setText("Cadru Didactic");
        jRadioButtonCadruDidactic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonCadruDidactic.setFocusable(false);
        jRadioButtonCadruDidactic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCadruDidacticActionPerformed(evt);
            }
        });

        buttonGroupRU.add(jRadioButtonDoctorand);
        jRadioButtonDoctorand.setText("Doctorand");
        jRadioButtonDoctorand.setFocusable(false);
        jRadioButtonDoctorand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDoctorandActionPerformed(evt);
            }
        });

        buttonGroupRU.add(jRadioButtonCercetator);
        jRadioButtonCercetator.setSelected(true);
        jRadioButtonCercetator.setText("Cercetator");
        jRadioButtonCercetator.setFocusable(false);
        jRadioButtonCercetator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCercetatorActionPerformed(evt);
            }
        });

        buttonGroupRU.add(jRadioButtonPersonalAdministrativ);
        jRadioButtonPersonalAdministrativ.setText("Personal Administrativ");
        jRadioButtonPersonalAdministrativ.setFocusable(false);
        jRadioButtonPersonalAdministrativ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPersonalAdministrativActionPerformed(evt);
            }
        });

        jLabelPostOcupat.setText("Post ocupat:");

        jTextFieldPostOcupat.setToolTipText("Postul ocupat ca cadru didactic");
        jTextFieldPostOcupat.setNextFocusableComponent(jTextFieldSpecializareDoctorand);

        jCheckBoxDirectorDepartament.setText("Director Departament");
        jCheckBoxDirectorDepartament.setToolTipText("Atentie, poate exista un singur Director de departament la un moment dat");

        jLabelSpecializareDoctorand.setText("Specializare:");

        jTextFieldSpecializareDoctorand.setToolTipText("Specializarea Doctorandului");
        jTextFieldSpecializareDoctorand.setNextFocusableComponent(jButtonAdaugaRU);

        jLabelDoneIconRU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/utils/img/rsz_doneicon3.png"))); // NOI18N
        jLabelDoneIconRU.setText("Adaugat cu succes");
        jLabelDoneIconRU.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelDoneIconRU.setIconTextGap(3);
        jLabelDoneIconRU.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabelDoneIconRU.setMinimumSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout jPanelRULayout = new javax.swing.GroupLayout(jPanelRU);
        jPanelRU.setLayout(jPanelRULayout);
        jPanelRULayout.setHorizontalGroup(
            jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneRU)
            .addGroup(jPanelRULayout.createSequentialGroup()
                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRULayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addComponent(jLabelSeAdaugaUn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addComponent(jLabelInterese)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldInterese))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRULayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdaugaRU, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGolesteCampuriRU, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelRULayout.createSequentialGroup()
                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRULayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefon)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelNume))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRULayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPrenume)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNume, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldTelefon)
                        .addComponent(jTextFieldEmail)
                        .addGroup(jPanelRULayout.createSequentialGroup()
                            .addComponent(jTextFieldPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(46, 46, 46)
                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDoctorand, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRULayout.createSequentialGroup()
                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCercetator, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonCadruDidactic)
                            .addComponent(jRadioButtonPersonalAdministrativ))
                        .addGap(38, 38, 38)
                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addComponent(jLabelPostOcupat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPostOcupat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxDirectorDepartament))
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addComponent(jLabelSpecializareDoctorand, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSpecializareDoctorand, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jLabelDoneIconRU, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
        );
        jPanelRULayout.setVerticalGroup(
            jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRULayout.createSequentialGroup()
                .addComponent(jScrollPaneRU, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNume)
                    .addComponent(jTextFieldNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInterese)
                    .addComponent(jTextFieldInterese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRULayout.createSequentialGroup()
                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRULayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelSeAdaugaUn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonCadruDidactic))
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrenume))))
                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTelefon)
                                    .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonCercetator)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonPersonalAdministrativ)))
                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelEmail))
                                    .addGroup(jPanelRULayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelSpecializareDoctorand)
                                            .addComponent(jTextFieldSpecializareDoctorand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanelRULayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonDoctorand)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(jPanelRULayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPostOcupat)
                            .addComponent(jTextFieldPostOcupat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxDirectorDepartament))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDoneIconRU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdaugaRU)
                    .addComponent(jButtonGolesteCampuriRU))
                .addContainerGap())
        );

        jTabbedPane.addTab("Resurse Umane", jPanelRU);

        jLabelResurseDisponibile.setText("Resurse disponibile:");

        jTableResurseFinanciare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sursa Fonduri", "Cuantum", "Moneda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneRF.setViewportView(jTableResurseFinanciare);

        jLabel1.setText("Sursa fonduri:");

        jLabel2.setText("Cuantum:");

        jLabel3.setText(" Moneda:");

        jTextFieldSursaFonduri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSursaFonduriActionPerformed(evt);
            }
        });

        jButtonAdaugaRF.setText("Adauga");
        jButtonAdaugaRF.setToolTipText("Salveaza datele introduse in baza de date");

        jButtonRenuntaRF.setText("Renunta");
        jButtonRenuntaRF.setToolTipText("Renunta la adaugare si goleste campurile completate");

        javax.swing.GroupLayout jPanelRFLayout = new javax.swing.GroupLayout(jPanelRF);
        jPanelRF.setLayout(jPanelRFLayout);
        jPanelRFLayout.setHorizontalGroup(
            jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRFLayout.createSequentialGroup()
                .addGroup(jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResurseDisponibile, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRFLayout.createSequentialGroup()
                        .addComponent(jScrollPaneRF, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSursaFonduri, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMoneda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCuantum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelRFLayout.createSequentialGroup()
                                .addComponent(jButtonAdaugaRF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRenuntaRF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanelRFLayout.setVerticalGroup(
            jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRFLayout.createSequentialGroup()
                .addComponent(jLabelResurseDisponibile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneRF, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRFLayout.createSequentialGroup()
                        .addGroup(jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldSursaFonduri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldCuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdaugaRF)
                            .addComponent(jButtonRenuntaRF))))
                .addGap(32, 32, 32))
        );

        jTabbedPane.addTab("Resurse Financiare", jPanelRF);

        buttonGroupRL.add(jRadioButtonAdaugaEchipament);
        jRadioButtonAdaugaEchipament.setSelected(true);
        jRadioButtonAdaugaEchipament.setText("Adauga un echipament");
        jRadioButtonAdaugaEchipament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdaugaEchipamentActionPerformed(evt);
            }
        });

        buttonGroupRL.add(jRadioButtonAdaugaSala);
        jRadioButtonAdaugaSala.setText("Adauga o sala");
        jRadioButtonAdaugaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdaugaSalaActionPerformed(evt);
            }
        });

        jLabelTipEchipament.setText("Tip echipament:");

        jLabelModelEchipament.setText("Model:");

        jLabelCodSala.setText("Cod Sala:");

        jLabelNumarLocuri.setText("Numar locuri:");

        jTableEchipamente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tip Echipament", "Model Echipament"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableEchipamente);

        jTableSali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cod Sala", "Nr. Locuri"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTableSali);

        jButtonAdaugaRL.setText("Adauga");
        jButtonAdaugaRL.setMaximumSize(new java.awt.Dimension(69, 23));
        jButtonAdaugaRL.setMinimumSize(new java.awt.Dimension(69, 23));
        jButtonAdaugaRL.setPreferredSize(new java.awt.Dimension(69, 23));
        jButtonAdaugaRL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdaugaRLActionPerformed(evt);
            }
        });

        jButtonGolesteCampuriRL.setText("Goleste campuri");
        jButtonGolesteCampuriRL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGolesteCampuriRLActionPerformed(evt);
            }
        });

        jLabelDoneIconRL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/utils/img/rsz_doneicon3.png"))); // NOI18N
        jLabelDoneIconRL.setText("Adaugare efectuata cu succes");
        jLabelDoneIconRL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelDoneIconRL.setIconTextGap(3);
        jLabelDoneIconRL.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabelDoneIconRL.setMinimumSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout jPanelRLLayout = new javax.swing.GroupLayout(jPanelRL);
        jPanelRL.setLayout(jPanelRLLayout);
        jPanelRLLayout.setHorizontalGroup(
            jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRLLayout.createSequentialGroup()
                        .addGroup(jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAdaugaEchipament, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonAdaugaSala))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipEchipament)
                            .addComponent(jTextFieldTipEchipamentRL)
                            .addComponent(jLabelModelEchipament)
                            .addComponent(jTextFieldModelEchipamentRL)
                            .addComponent(jLabelCodSala)
                            .addComponent(jTextFieldCodSalaRL)
                            .addComponent(jLabelNumarLocuri)
                            .addComponent(jTextFieldNrLocuriRL, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(jPanelRLLayout.createSequentialGroup()
                        .addComponent(jButtonAdaugaRL, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGolesteCampuriRL))
                    .addComponent(jLabelDoneIconRL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelRLLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldCodSalaRL, jTextFieldModelEchipamentRL, jTextFieldNrLocuriRL, jTextFieldTipEchipamentRL});

        jPanelRLLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdaugaRL, jButtonGolesteCampuriRL});

        jPanelRLLayout.setVerticalGroup(
            jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRLLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRLLayout.createSequentialGroup()
                        .addGroup(jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRLLayout.createSequentialGroup()
                                .addGroup(jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonAdaugaEchipament)
                                    .addGroup(jPanelRLLayout.createSequentialGroup()
                                        .addComponent(jLabelTipEchipament)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldTipEchipamentRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelModelEchipament)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldModelEchipamentRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106)
                                .addComponent(jLabelCodSala))
                            .addGroup(jPanelRLLayout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jRadioButtonAdaugaSala)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodSalaRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNumarLocuri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNrLocuriRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDoneIconRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdaugaRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGolesteCampuriRL))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Resurse Logistice", jPanelRL);

        javax.swing.GroupLayout jPanelSFLayout = new javax.swing.GroupLayout(jPanelSF);
        jPanelSF.setLayout(jPanelSFLayout);
        jPanelSFLayout.setHorizontalGroup(
            jPanelSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        jPanelSFLayout.setVerticalGroup(
            jPanelSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("State de Functii", jPanelSF);

        javax.swing.GroupLayout jPanelORLayout = new javax.swing.GroupLayout(jPanelOR);
        jPanelOR.setLayout(jPanelORLayout);
        jPanelORLayout.setHorizontalGroup(
            jPanelORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        jPanelORLayout.setVerticalGroup(
            jPanelORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Orar", jPanelOR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("t1ResurseUmane");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSursaFonduriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSursaFonduriActionPerformed
        // TODO add your handlving code here:
    }//GEN-LAST:event_jTextFieldSursaFonduriActionPerformed

    //pentru ResurseUmane
    
    private void jRadioButtonPersonalAdministrativActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPersonalAdministrativActionPerformed
        jLabelPostOcupat.setVisible(false);
        jTextFieldPostOcupat.setVisible(false);
        jCheckBoxDirectorDepartament.setVisible(false);
        jLabelSpecializareDoctorand.setVisible(false);
        jTextFieldSpecializareDoctorand.setVisible(false);
    }//GEN-LAST:event_jRadioButtonPersonalAdministrativActionPerformed

    private void jRadioButtonCercetatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCercetatorActionPerformed
        jLabelPostOcupat.setVisible(false);
        jTextFieldPostOcupat.setVisible(false);
        jCheckBoxDirectorDepartament.setVisible(false);
        jLabelSpecializareDoctorand.setVisible(false);
        jTextFieldSpecializareDoctorand.setVisible(false);
    }//GEN-LAST:event_jRadioButtonCercetatorActionPerformed

    private void jRadioButtonDoctorandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDoctorandActionPerformed
        jLabelPostOcupat.setVisible(false);
        jTextFieldPostOcupat.setVisible(false);
        jCheckBoxDirectorDepartament.setVisible(false);
        jLabelSpecializareDoctorand.setVisible(true);
        jTextFieldSpecializareDoctorand.setVisible(true);
    }//GEN-LAST:event_jRadioButtonDoctorandActionPerformed

    private void jRadioButtonCadruDidacticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCadruDidacticActionPerformed
        jLabelPostOcupat.setVisible(true);
        jTextFieldPostOcupat.setVisible(true);
        jCheckBoxDirectorDepartament.setVisible(true);
        jLabelSpecializareDoctorand.setVisible(false);
        jTextFieldSpecializareDoctorand.setVisible(false);

    }//GEN-LAST:event_jRadioButtonCadruDidacticActionPerformed

    private void jButtonAdaugaRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdaugaRUActionPerformed
        if(jRadioButtonCadruDidactic.isSelected()){
            try{
                if(this.controller.addCadruDidactic(jTextFieldNume.getText().trim(),
                                            jTextFieldPrenume.getText().trim(),
                                            jTextFieldTelefon.getText().trim(),
                                            jTextFieldEmail.getText().trim(),
                                            jTextFieldInterese.getText().trim(),
                                            generator.nextPassword(),
                                            jTextFieldPostOcupat.getText().trim(),
                                            jCheckBoxDirectorDepartament.isSelected())  != null){
                this.jLabelDoneIconRU.setVisible(true);   
                this.clearFieldsRU();
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
        if(jRadioButtonPersonalAdministrativ.isSelected()){
            try{
                if(this.controller.addPersonalAdministrativ(jTextFieldNume.getText().trim(),
                                            jTextFieldPrenume.getText().trim(),
                                            jTextFieldTelefon.getText().trim(),
                                            jTextFieldEmail.getText().trim(),
                                            jTextFieldInterese.getText().trim(),
                                            generator.nextPassword()) != null){
                this.jLabelDoneIconRU.setVisible(true);   
                this.clearFieldsRU();  
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if(jRadioButtonCercetator.isSelected()){
            
            
        }
        
        if(jRadioButtonDoctorand.isSelected()){
            
            
        }
        
        commonController.updateResursaUmanaTableModel();    
        //this.clearFieldsRU();     -trebuie doar daca s-a facut cu succes adaugarea
        t.start();//aici dispare jLabel cu adaugat cu succes
    }//GEN-LAST:event_jButtonAdaugaRUActionPerformed
    
    //pentru ResurseLogistice:
    
    private void jRadioButtonAdaugaEchipamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdaugaEchipamentActionPerformed
        jTextFieldCodSalaRL.setEditable(false);
        jTextFieldNrLocuriRL.setEditable(false);
        jTextFieldModelEchipamentRL.setEditable(true);
        jTextFieldTipEchipamentRL.setEditable(true);
    }//GEN-LAST:event_jRadioButtonAdaugaEchipamentActionPerformed

    private void jRadioButtonAdaugaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdaugaSalaActionPerformed
        jTextFieldCodSalaRL.setEditable(true);
        jTextFieldNrLocuriRL.setEditable(true);
        jTextFieldModelEchipamentRL.setEditable(false);
        jTextFieldTipEchipamentRL.setEditable(false);
    }//GEN-LAST:event_jRadioButtonAdaugaSalaActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        amf.disposeAdminFrame();
        loginController.makeVisibleLoginFrame();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonGolesteCampuriRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGolesteCampuriRUActionPerformed
        this.clearFieldsRU();
    }//GEN-LAST:event_jButtonGolesteCampuriRUActionPerformed

    private void jButtonAdaugaRLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdaugaRLActionPerformed
        if(jRadioButtonAdaugaEchipament.isSelected()){
            try{
                if(this.controller.addEchipament(jTextFieldTipEchipamentRL.getText().trim(), 
                                                 jTextFieldModelEchipamentRL.getText().trim()) 
                                                 != null){
                    this.jLabelDoneIconRL.setVisible(true);
                    this.clearFieldsRL();
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(jRadioButtonAdaugaSala.isSelected()){
            try{
                if(this.controller.addSala(jTextFieldCodSalaRL.getText().trim(), 
                                           Integer.parseInt(jTextFieldNrLocuriRL.getText())) 
                                           != null){
                    this.jLabelDoneIconRL.setVisible(true);
                    this.clearFieldsRL();
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
            }
        }
        //aici trebuie sa vina update-ul la table-ul de resurse logistice cand o sa fie implementat si care se apeleaza
        //dupa fiecare adaugare/modificare
        t.start();//aici dispare jLabel cu adaugat cu succes
    }//GEN-LAST:event_jButtonAdaugaRLActionPerformed

    private void jButtonGolesteCampuriRLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGolesteCampuriRLActionPerformed
        this.clearFieldsRL();
    }//GEN-LAST:event_jButtonGolesteCampuriRLActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRL;
    private javax.swing.ButtonGroup buttonGroupRU;
    private javax.swing.JButton jButtonAdaugaRF;
    private javax.swing.JButton jButtonAdaugaRL;
    private javax.swing.JButton jButtonAdaugaRU;
    private javax.swing.JButton jButtonGolesteCampuriRL;
    private javax.swing.JButton jButtonGolesteCampuriRU;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRenuntaRF;
    private javax.swing.JCheckBox jCheckBoxDirectorDepartament;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCodSala;
    private javax.swing.JLabel jLabelDoneIconRL;
    private javax.swing.JLabel jLabelDoneIconRU;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGreeting;
    private javax.swing.JLabel jLabelInterese;
    private javax.swing.JLabel jLabelModelEchipament;
    private javax.swing.JLabel jLabelNumarLocuri;
    private javax.swing.JLabel jLabelNume;
    private javax.swing.JLabel jLabelPostOcupat;
    private javax.swing.JLabel jLabelPrenume;
    private javax.swing.JLabel jLabelResurseDisponibile;
    private javax.swing.JLabel jLabelSeAdaugaUn;
    private javax.swing.JLabel jLabelSpecializareDoctorand;
    private javax.swing.JLabel jLabelTelefon;
    private javax.swing.JLabel jLabelTipEchipament;
    private javax.swing.JPanel jPanelOR;
    private javax.swing.JPanel jPanelRF;
    private javax.swing.JPanel jPanelRL;
    private javax.swing.JPanel jPanelRU;
    private javax.swing.JPanel jPanelSF;
    private javax.swing.JPanel jPanelTopPanel;
    private javax.swing.JRadioButton jRadioButtonAdaugaEchipament;
    private javax.swing.JRadioButton jRadioButtonAdaugaSala;
    private javax.swing.JRadioButton jRadioButtonCadruDidactic;
    private javax.swing.JRadioButton jRadioButtonCercetator;
    private javax.swing.JRadioButton jRadioButtonDoctorand;
    private javax.swing.JRadioButton jRadioButtonPersonalAdministrativ;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPaneRF;
    private javax.swing.JScrollPane jScrollPaneRU;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableEchipamente;
    private javax.swing.JTable jTableRU;
    private javax.swing.JTable jTableResurseFinanciare;
    private javax.swing.JTable jTableSali;
    private javax.swing.JTextField jTextFieldCodSalaRL;
    private javax.swing.JTextField jTextFieldCuantum;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldInterese;
    private javax.swing.JTextField jTextFieldModelEchipamentRL;
    private javax.swing.JTextField jTextFieldMoneda;
    private javax.swing.JTextField jTextFieldNrLocuriRL;
    private javax.swing.JTextField jTextFieldNume;
    private javax.swing.JTextField jTextFieldPostOcupat;
    private javax.swing.JTextField jTextFieldPrenume;
    private javax.swing.JTextField jTextFieldSpecializareDoctorand;
    private javax.swing.JTextField jTextFieldSursaFonduri;
    private javax.swing.JTextField jTextFieldTelefon;
    private javax.swing.JTextField jTextFieldTipEchipamentRL;
    // End of variables declaration//GEN-END:variables

    private AdministratorController controller;
    private LoginController loginController;
    private String loggedUser;
    private AdminMainFrame amf;
    private RandomPass generator;
    private CommonController commonController;
    private Timer t;
    
    
    
    
    public JTable getTableRU(){
        return jTableRU;
    }
    public void updateRUtable(){
        jTableRU.setModel(commonController.getResursaUmanaTableModel());
       
    }
    private void clearFieldsRU(){
        jTextFieldNume.setText("");
        jTextFieldPrenume.setText("");
        jTextFieldTelefon.setText("");
        jTextFieldEmail.setText("");
        jTextFieldInterese.setText("");
        jTextFieldPostOcupat.setText("");
        jTextFieldSpecializareDoctorand.setText("");
        jCheckBoxDirectorDepartament.setSelected(false);
    }
    private void clearFieldsRL(){
        jTextFieldCodSalaRL.setText("");
        jTextFieldNrLocuriRL.setText("");
        jTextFieldModelEchipamentRL.setText("");
        jTextFieldTipEchipamentRL.setText("");
    }
    
//    public static void waitfor (int n){
//        long t0, t1;
//        t0 =  System.currentTimeMillis();
//        do{
//            t1 = System.currentTimeMillis();
//        }while (t1 - t0 < n);
//    }
    
}
